image::https://badges.gitter.im/Join%20Chat.svg["Gitter",link="https://gitter.im/spring-cloud/spring-cloud-security?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]


include::intro.adoc[]

== Upgrading to 1.1.0

Most of the OAuth2 features moved from this project to Spring Boot 1.3, so from version 1.1 things are a little different here. Here
is a guide to the available features as they were in 1.0, but with new names and slightly new APIs.

As in 1.0, an app will activate `@EnableOAuth2Sso` if you bind provide some
following properties in the `Environment`.

You can still customize the access rules in an SSO application, but instead
of a specific callback (the old `OAuth2SsoConfigurer`) all you do now is
add `@EnableOAuth2Sso` to a `WebSecurityConfigurerAdapter`.
For example if you want the resources under "/ui/**" to be protected with OAuth2:

[source,java,indent=0]
----
	@Configuration
	@EnableOAuth2Sso
	@EnableAutoConfiguration
	protected static class TestConfiguration extends WebSecurityConfigurerAdapter {
		@Override
		public void match(RequestMatchers matchers) {
			matchers.antMatchers("/ui/**")
                .authorizeRequests().anyRequest().authenticated();
		}
	}
----

In this case the rest of the application will default to the normal
Spring Boot access control for other paths (Basic authentication, or 
whatever custom filters you put in place).

There is no `@EnableOAuth2Resource` annotation in Spring Cloud 1.1.
You just use the regular `@EnableResourceServer` from Spring OAuth.

== Building

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/building.adoc[]

== Contributing

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]
