= Spring Cloud Security
:github: https://github.com/spring-cloud/spring-cloud-security
:githubmaster: {github}/tree/master
:docslink: {githubmaster}/src/main/asciidoc

include::intro.adoc[]

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing-docs.adoc[]

== Quickstart

include::quickstart.adoc[]

== More Detail

=== Single Sign On

NOTE: All of the OAuth2 SSO and resource server features moved to Spring Boot
in version 1.3. You can find documentation in the 
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/[Spring Boot user guide].

=== Token Relay

A Token Relay is where an OAuth2 consumer acts as a Client and
forwards the incoming token to outgoing resource requests. The
consumer can be a pure Client (like an SSO application) or a Resource
Server.

==== Client Token Relay

If your app has a
http://cloud.spring.io/spring-cloud.html#netflix-zuul-reverse-proxy[Spring
Cloud Zuul] embedded reverse proxy (using `@EnableZuulProxy`) then you
can ask it to forward OAuth2 access tokens downstream to the services
it is proxying. Thus the SSO app above can be enhanced simply like this:

.app.groovy
[source,java]
----
@Controller
@EnableOAuth2Sso
@EnableZuulProxy
class Application {
  
}
----

and it will (in addition to loggin the user in and grabbing a token)
pass the authentication token downstream to the `/proxy/*`
services. If those services are implemented with
`@EnableOAuth2Resource` then they will get a valid token in the
correct header.

How does it work? The `@EnableOAuth2Sso` annotation pulls in
`spring-cloud-starter-security` (which you could do manually in a
traditional app), and that in turn triggers some autoconfiguration for
a `ZuulFilter`, which itself is activated because Zuul is on the
classpath (via `@EnableZuulProxy`). The
{githubmaster}/src/main/java/org/springframework/cloud/security/oauth2/proxy/OAuth2TokenRelayFilter.java[filter]
just extracts an access token from the currently authenticated user,
and puts it in a request header for the downstream requests.

==== Resource Server Token Relay

If your app has `@EnableOAuth2Resource` and also is a Client (i.e. it
has a `spring.oauth2.client.clientId`, even if it doesn't use it),
then the `OAuth2RestOperations` that is provided for `@Autowired`
users by Spring Cloud (it is declared as `@Primary`) will also forward
tokens. If you don't want to forward tokens (and that is a valid
choice, since you might want to act as yourself, rather than the
client that sent you the token), then you only need to create your own
`OAuth2RestOperations` instead of autowiring the default one. Here's
a basic example showing the use of the autowired rest template ("foo.com"
is a Resource Server accepting the same tokens as the surrounding app):

.MyController.java
[source,java]
----
@Autowired
private OAuth2RestOperations restTemplate;
    
@RequestMapping("/relay")
public String relay() {
    ResponseEntity<String> response = 
      restTemplate.getForEntity("https://foo.com/bar", String.class);
    return "Success! (" + response.getBody() + ")";
}
----

== Configuring Authentication Downstream of a Zuul Proxy

You can control the authorization behaviour downstream of an
`@EnableZuulProxy` through the `proxy.auth.*` settings. Example:

.application.yml
[source,yaml]
----
proxy:
  auth:
    routes:
      customers: oauth2
      stores: passthru
      recommendations: none
----

In this example the "customers" service gets an OAuth2 token relay,
the "stores" service gets a passthrough (the authorization header is
just passed downstream), and the "recommendations" service has its
authorization header removed. The default behaviour is to do a token
relay if there is a token available, and passthru otherwise.

See
{githubmaster}/src/main/java/org/springframework/cloud/security/oauth2/proxy/ProxyAuthenticationProperties[
ProxyAuthenticationProperties] for full details.
